apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocab-app
  namespace: vocab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vocab-app
  template:
    metadata:
      labels:
        app: vocab-app
    spec:
      containers:
        - name: vocab-app
          image: harbor.watasoftware.com/demo/vocab-app:latest   # Cập nhật image tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vocab-app
  namespace: vocab
spec:
  selector:
    app: vocab-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vocab-app
  namespace: demo-01
spec:
  ingressClassName: traefik
  rules:
    - host: vocab.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vocab-app
                port:
                  number: 3000
