apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocab-app
  namespace: vocab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vocab-app
  template:
    metadata:
      labels:
        app: vocab-app
    spec:
      containers:
        - name: vocab-app
          image: harbor.watasoftware.com/vocab-app/vocab-app:latest
          #imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: vocab-app
  namespace: vocab
spec:
  selector:
    app: vocab-app
  ports:
    - name: http
      port: 4173
      targetPort: 4173
      protocol: TCP
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vocab-app
  namespace: vocab
spec:
  ingressClassName: traefik
  rules:
    - host: vocab.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vocab-app
                port:
                  number: 4173
