apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vocab

resources:
- deployment.yaml   # File YAML của ứng dụng vocab-app

images:
  - name: harbor.watasoftware.com/vocab-app/vocab-app
    newTag: "24"
